*********************************************************************************
#RQ1:
python run_own.py --output_dir=./saved_models/RQ1_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_train --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_all_cdata.jsonl --eval_vul_data_file=../dataset/RQ1_512/valid_vul_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_cdata.jsonl --epoch 24 --block_size 512 --train_batch_size 24 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl 2>&1 | tee RQ1_512_24_new.log

python run_own.py --output_dir=./saved_models/RQ1_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_all_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_cdata.jsonl --epoch 12 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
 
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_cdata.jsonl -p saved_models/RQ1_512_24_new/predictions.txt


python run_own.py --output_dir=./saved_models/RQ1_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1/test_cdata.jsonl --epoch 16 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ1/test_cdata.jsonl -p saved_models/RQ1_512_24_new/predictions_not.txt

# *********************************************************************************
#RQ3:
python run_own.py --output_dir=./saved_models/RQ1_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/predictions_vul.txt

python run_own.py --output_dir=./saved_models/RQ1_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_all_cdata.jsonl --epoch 16 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_all_cdata.jsonl -p saved_models/RQ1_512_24_new/predictions_all.txt


python run_own.py --output_dir=./saved_models/RQ1_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ3/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ3/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/predictions_vul_not.txt

python run_own.py --output_dir=./saved_models/RQ1_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ3/test_all_cdata.jsonl --epoch 16 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ3/test_all_cdata.jsonl -p saved_models/RQ1_512_24_new/predictions_all_not.txt

# *********************************************************************************
# #RQ2:
python run_own.py --output_dir=./saved_models/RQ2_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_train --train_data_file=../dataset/RQ2_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ2_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ2_512/valid_all_cdata.jsonl --test_data_file=../dataset/RQ2_512/test_cdata.jsonl --epoch 24 --block_size 512 --train_batch_size 24 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl 2>&1 | tee RQ2_512_24_new.log

python run_own.py --output_dir=./saved_models/RQ2_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ2_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ2_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ2_512/valid_all_cdata.jsonl --test_data_file=../dataset/RQ2_512/test_cdata.jsonl --epoch 16 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ2_512/test_cdata.jsonl -p saved_models/RQ2_512_24_new/predictions.txt


python run_own.py --output_dir=./saved_models/RQ2_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ2_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ2_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ2_512/valid_cdata.jsonl --test_data_file=../dataset/RQ2/test_cdata.jsonl --epoch 16 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ2/test_cdata.jsonl -p saved_models/RQ2_512_24_new/predictions_not.txt
# *********************************************************************************
# #RQ4:
python run_own.py --output_dir=./saved_models/RQ4_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_train --train_data_file=../dataset/RQ4_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ4_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ4_512/valid_all_cdata.jsonl --test_data_file=../dataset/RQ4_512/test_cdata.jsonl --epoch 24 --block_size 512 --train_batch_size 24 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python run_own.py --output_dir=./saved_models/RQ4_512_24_new --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ4_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ4_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ4_512/valid_cdata.jsonl --test_data_file=../dataset/RQ4/test_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ4/test_cdata.jsonl -p saved_models/RQ4_512_24_new/predictions_not.txt

# *********************************************************************************
# For each epoch:
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-0 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-1 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-2 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-3 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-4 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-5 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-6 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-7 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-8 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-9 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-10 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-11 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-12 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-13 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-14 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-15 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-16 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-17 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-18 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-19 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-20 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-21 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-22 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-23 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-0/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-1/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-2/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-3/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-4/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-5/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-6/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-7/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-8/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-9/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-10/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-11/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-12/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-13/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-14/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-15/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-16/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-17/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-18/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-19/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-20/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-21/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-22/predictions_vul.txt
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-23/predictions_vul.txt

python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-21 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_all_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_cdata.jsonl --epoch 12 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl
 
python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-21/predictions.txt


python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-21 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1/test_cdata.jsonl --epoch 16 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ1/test_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-21/predictions_not.txt



python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-21 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-21/predictions_vul.txt

python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-21 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ1_512/test_all_cdata.jsonl --epoch 16 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ1_512/test_all_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-21/predictions_all.txt


python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-21 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ3/test_vul_cdata.jsonl --epoch 8 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ3/test_vul_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-21/predictions_vul_not.txt

python run_own.py --output_dir=./saved_models/RQ1_512_24_new/checkpoint-21 --model_type=roberta --tokenizer_name=../models/codebert --model_name_or_path=../models/codebert --do_test --train_data_file=../dataset/RQ1_512/train_cdata.jsonl --train_vul_data_file=../dataset/RQ1_512/train_vul_cdata.jsonl --eval_data_file=../dataset/RQ1_512/valid_cdata.jsonl --test_data_file=../dataset/RQ3/test_all_cdata.jsonl --epoch 16 --block_size 512 --train_batch_size 40 --eval_batch_size 64 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 --cnn_size 128 --filter_size 3 --d_size 128 --pkl_file=short_3path_cdata_nobalance.pkl

python ../evaluator/evaluator.py -a ../dataset/RQ3/test_all_cdata.jsonl -p saved_models/RQ1_512_24_new/checkpoint-21/predictions_all_not.txt